/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geili_koudai_util_PatchUtil */

#ifndef _Included_com_geili_koudai_util_PatchUtil
#define _Included_com_geili_koudai_util_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geili_koudai_util_PatchUtil
 * Method:    createAPKByDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_geili_koudai_util_PatchUtil_createAPKByDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_geili_koudai_util_PatchUtil
 * Method:    createDiffData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_geili_koudai_util_PatchUtil_createDiffData
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
